apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yihao-local
  annotations:
    defaultVolumeType: "local"
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - yihao-pve-debian
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: n100-local
  annotations:
    defaultVolumeType: local
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - n100
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: opiai20t-512-local
  annotations:
    defaultVolumeType: local
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - opiai20t-512
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: musepipro-512-local
  annotations:
    defaultVolumeType: local
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - musepipro-512
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: opi5-local
  annotations:
    defaultVolumeType: local
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - opi5
volumeBindingMode: WaitForFirstConsumer
