apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
- job.yaml
configMapGenerator:
- name: harbor-cache-scripts
  files:
  - configure-cache.py
generatorOptions:
  disableNameSuffixHash: true
