apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hysteria2
helmGlobals:
  chartHome: helm
helmCharts:
- name: hysteria2
  version: 0.1.0
  releaseName: hysteria2
  namespace: hysteria2
  valuesFile: values/hysteria2-0.1.0.yaml
components:
- ../../components/image-prefix
