apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-services
  namespace: platform-certificates
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  secretName: platform-services-tls
  dnsNames:
  - '*.k8s.yhzone.top'
  - harbor.yhzone.top
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
