apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-esa
  {{- if .Values.esaIngress.expose }}
  labels:
    networking.yhzone.top/exposure: public
  {{- end }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    networking.yhzone.top/publish-dns: {{ .Values.esaIngress.publishDNS | quote }}
spec:
  ingressClassName: traefik-public
  tls:
  - hosts: [{{ .Values.esaIngress.host | quote }}]
    secretName: {{ .Release.Name }}-esa-tls
  rules:
  - host: {{ .Values.esaIngress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-public
            port:
              number: 80
