apiVersion: v1
kind: Namespace
metadata:
  name: oes-storage
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oes-disks
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oes-hdd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 450Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oes-disks
  local:
    path: /home/yihao/k8s/storage/hdd/data
  claimRef:
    name: oes-hdd
    namespace: oes-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - oes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oes-hdd
  namespace: oes-storage
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: oes-disks
  volumeName: oes-hdd
  resources:
    requests:
      storage: 450Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oes-ssd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 230Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oes-disks
  local:
    path: /home/yihao/k8s/storage/ssd/data
  claimRef:
    name: oes-ssd
    namespace: oes-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - oes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oes-ssd
  namespace: oes-storage
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: oes-disks
  volumeName: oes-ssd
  resources:
    requests:
      storage: 230Gi
