apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.5.3/manifests/install.yaml
- project.yaml
patches:
- path: patches/server-config.yaml
- path: patches/server-deployment.yaml
- path: patches/kustomize-config.yaml
