apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yihao
  namespace: argocd
spec:
  description: yihao cluster infrastructure
  sourceRepos:
  - https://github.com/eWloYW8/argo-cd.yhzone.top.git
  - https://charts.jetstack.io
  - https://helm.goharbor.io
  - https://kubernetes-sigs.github.io/headlamp/
  - https://kubernetes-sigs.github.io/external-dns/
  - https://traefik.github.io/charts
  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
