apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-support
  namespace: argocd
spec:
  project: yihao
  source:
    repoURL: https://github.com/eWloYW8/argo-cd.yhzone.top.git
    targetRevision: main
    path: platform/harbor-support
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: harbor-postgresql
    namespace: harbor
    jqPathExpressions:
    - .spec.volumeClaimTemplates[].status
