apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../platform/storage
- argocd.yaml
- ../../platform/project
- cert-manager.yaml
- certificates.yaml
- headlamp.yaml
- harbor-support.yaml
- harbor.yaml
- ../../platform/headlamp-access
- harbor-cache.yaml
- caddy-internal.yaml
