apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yihao-secrets
  namespace: argocd
spec:
  project: yihao-secrets
  source:
    repoURL: git@github.com:eWloYW8/argo-cd-secrets.yhzone.top.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
