apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yihao-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  description: Private unencrypted service Secrets; no workloads or cluster-scoped
    resources
  sourceRepos:
  - git@github.com:eWloYW8/argo-cd-secrets.yhzone.top.git
  destinations:
  - server: https://kubernetes.default.svc
    namespace: ascend-compiler-explorer
  - server: https://kubernetes.default.svc
    namespace: cert-manager
  - server: https://kubernetes.default.svc
    namespace: easytier-web
  - server: https://kubernetes.default.svc
    namespace: external-dns
  - server: https://kubernetes.default.svc
    namespace: funasr-nano
  - server: https://kubernetes.default.svc
    namespace: harbor
  - server: https://kubernetes.default.svc
    namespace: hysteria2
  - server: https://kubernetes.default.svc
    namespace: neverrun
  - server: https://kubernetes.default.svc
    namespace: new-api
  - server: https://kubernetes.default.svc
    namespace: subcon
  - server: https://kubernetes.default.svc
    namespace: vaultwarden
  - server: https://kubernetes.default.svc
    namespace: zhiyun-tools
  - server: https://kubernetes.default.svc
    namespace: zju-autosign
  - server: https://kubernetes.default.svc
    namespace: zjulibbooking
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
  - group: ''
    kind: Secret
