apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
helmGlobals:
  chartHome: helm
helmCharts:
- name: vaultwarden
  version: 0.1.0
  releaseName: vaultwarden
  namespace: vaultwarden
  valuesFile: values/vaultwarden-0.1.0.yaml
components:
- ../../components/image-prefix
