apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shell
helmGlobals:
  chartHome: helm
helmCharts:
- name: shell
  version: 0.1.0
  releaseName: shell
  namespace: shell
  valuesFile: values/shell-0.1.0.yaml
components:
- ../../components/image-prefix
