apiVersion: v1
kind: Service
metadata:
  name: shell-public
  annotations:
    traefik.ingress.kubernetes.io/service.nativelb: 'true'
spec:
  trafficDistribution: PreferSameNode
  selector:
    app.kubernetes.io/name: shell
  ports:
  - name: http
    port: 8080
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shell-public
  {{- if .Values.publicIngress.expose }}
  labels:
    networking.yhzone.top/exposure: public
  {{- end }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    networking.yhzone.top/publish-dns: {{ .Values.publicIngress.publishDNS | quote }}
spec:
  ingressClassName: traefik-public
  tls:
  - hosts: [{{ .Values.publicIngress.host | quote }}]
    secretName: shell-public-tls
  rules:
  - host: {{ .Values.publicIngress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shell-public
            port:
              number: 8080
