apiVersion: v1
kind: PersistentVolume
metadata:
  name: yihao-shell-files
spec:
  capacity:
    storage: {{ .Values.storageSize }}
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: yihao-local
  local:
    path: {{ .Values.storagePath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [{{ .Values.node | quote }}]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shell-files
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: yihao-local
  volumeName: yihao-shell-files
  resources:
    requests:
      storage: {{ .Values.storageSize }}
