apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: easytier-web
helmGlobals:
  chartHome: helm
helmCharts:
- name: easytier-web
  version: 0.1.0
  releaseName: easytier-web
  namespace: easytier-web
  valuesFile: values/easytier-web-0.1.0.yaml
components:
- ../../components/image-prefix
resources:
- resources/namespace.yaml
