apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
- resources
helmCharts:
- name: harbor
  repo: https://helm.goharbor.io
  version: 1.19.2
  releaseName: harbor
  namespace: harbor
  includeCRDs: true
  valuesFile: values/harbor-1.19.2.yaml
patches:
- path: patches/dns.yaml
