apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hysteria2-tls
spec:
  secretName: hysteria2-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
  - '*.yhzone.top'
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  renewBefore: 720h
