apiVersion: v1
kind: Service
metadata:
  name: hysteria2-udp
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
  - name: hysteria
    port: 30443
    targetPort: hysteria
    protocol: UDP
