{{- if .Values.publicBasicAuth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-public-auth
  labels:
    networking.yhzone.top/exposure: public
spec:
  basicAuth:
    secret: {{ .Values.publicBasicAuth.secretName }}
    realm: Public services
    removeHeader: true
{{- end }}
