apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: funasr-nano
helmGlobals:
  chartHome: helm
helmCharts:
- name: funasr-nano
  version: 0.1.0
  releaseName: funasr-nano
  namespace: funasr-nano
  valuesFile: values/funasr-nano-0.1.0.yaml
components:
- ../../components/image-prefix
