apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- resources/namespace.yaml
- resources
patches:
- target:
    group: apps
    version: v1
    kind: Deployment|StatefulSet
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector/node.yhzone.top~1role
      value: core
    - op: add
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-dex-server|argocd-repo-server|argocd-redis
  patch: |-
    - op: add
      path: /spec/template/spec/initContainers/0/imagePullPolicy
      value: IfNotPresent
