apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zhiyun-tools
helmGlobals:
  chartHome: helm
helmCharts:
- name: zhiyun-tools
  version: 0.1.0
  releaseName: zhiyun-tools
  namespace: zhiyun-tools
  valuesFile: values/zhiyun-tools-0.1.0.yaml
components:
- ../../components/image-prefix
resources:
- resources/namespace.yaml
