apiVersion: v1
kind: Service
metadata:
  name: easytier-web
spec:
  selector:
    app.kubernetes.io/name: easytier-web
  ports:
  - name: http
    port: 11211
    targetPort: http
  - name: rpc
    port: 22020
    targetPort: rpc
