apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: subcon
helmGlobals:
  chartHome: helm
helmCharts:
- name: subcon
  version: 0.1.0
  releaseName: subcon
  namespace: subcon
  valuesFile: values/subcon-0.1.0.yaml
components:
- ../../components/image-prefix
resources:
- resources/namespace.yaml
